import Head from "next/head";

import {Inter} from "@next/font/google";
import Layout from "@/components/Layout";
import InputForm from "@/components/InputForm";
import Card from "@/components/Card";

const inter = Inter({subsets: ["latin"]});

import {CARD_DATA} from '@/data/data'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <h2 className="text-2xl font-semibold">
                    Properties to Rent in New Work
                </h2>
                <InputForm/>
                <div className="mt-4 space-y-4">
                    {CARD_DATA.map((item) => (
                        <Card
                            key={item.id}
                            title={item.title}
                            description={item.description}
                            images={item.images}
                            slug={item.slug}
                        />
                    ))}
                </div>
            </Layout>
        </>
    );
}
